start_date: "2023-01-01"
end_date: "2023-01-03"

use_temp_apod_data: False
use_hdurl: False

supabase_upload: True

save_url: True
save_media_type: True
save_content_type: False
save_color_palette: True
save_filterable_colors: True
save_img_width: True
save_img_height: True
save_img_wh_ratio: True
save_is_animated: True

generate_combined_image: True

extcolors_tolerance: 32
extcolors_limit: 4